name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --https://github.com/deocheng/mi-gpt/edit --tag deo_migpt:crpi-q4h0yzj48nwvvc1g.cn-hangzhou.personal.cr.aliyuncs.com
